### ISSUE TITLE
Resource.designer.cs has 31 errors

### ISSUE THREAD

**Issue by simondebaecke** [jamesmontemagno/XamDroid.StickyListHeaders#10]
Hi James !

Since Xamarin.Android.Support.v7.AppCompat v23 updated in my app, 31 errors occur in resource.designer.cs (like global::com.refractored.Resource.Attribute.barSize) because of the changes between versions. It's weird since I didn't see any reference to this package in this library ... But it's the only dependency that cause me some errors. Do you know how to fix that exactly ?

Thank you in advance for your help !

**Comment by simondebaecke** [comment]
It was your other library fault : https://github.com/jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android/ and his dependency AppCompat v22. ;)

**Comment by jamesmontemagno** [comment]
I updated that one to 23 a little bit ago
