### ISSUE TITLE
Not obsoleted by https://components.xamarin.com/view/stickyheader?

### ISSUE THREAD

**Issue by ThreeScreenStudios** [jamesmontemagno/XamDroid.StickyListHeaders#8]
Hi,

I came across your library when looking for how to create sticky headers with Xamarin.Android. I'm looking for a library to have a header that sticks to the top, that also changes as you scroll through list groups - the Xamarin component sticky header doesn't appear to do this? I was wondering, is there something I'm missing, or do you have to create a custom implementation in order to get the component to work (as opposed to your library, which looks to have the functionality built in)? Either way, thanks for creating StickyListHeaders!

**Comment by jamesmontemagno** [comment]
I am pretty sure that everything still works just fine for this repo. I will re-test today. THere is also a new component: http://components.xamarin.com/view/PRAPinnedListView

I have removed the obsolete as yes they are different

**Comment by ThreeScreenStudios** [comment]
@jamesmontemagno thanks for the info! Much appreciated, and I'll start using your lib today :)
