### ISSUE TITLE
Pull To Refresh

### ISSUE THREAD

**Issue by Gunner92** [jamesmontemagno/XamDroid.StickyListHeaders#9]
Hi James 
I am using your stickyListHeader for list. But i must use pull to refresh for my list. How can i implement pull to refresh  this library.Can u help me about this?
Thanks Burak

**Comment by jamesmontemagno** [comment]
Sure thing, you can wrap any Android control in a SwipeRefreshLayout. See the blog here: http://blog.xamarin.com/swipe-to-refresh-added-to-android-support-v4-component/
